[tools]
claude-code = "latest"
codex = "latest"
crystal = "latest"
erlang = "latest"
"github:BurntSushi/ripgrep" = "latest"
go = "latest"
hishtory = "latest"
jq = "latest"
rust = "latest"
starship = "latest"
zoxide = "latest"
elixir = "latest"
age = "latest"
bitwarden = "latest"
github-cli = "latest"
aws = { version = "latest", symlink_bins = "true" }
uv = "latest"
chezmoi = "latest"

[settings]
env_shell_expand = false
