# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
[╭─ [$username](italic)$directory$git_branch$git_status](bold green)
[│](green) $all
[╰─ $character](bold green)"""
scan_timeout = 30

[battery]
disabled = true

[character]
error_symbol = "[ψ](bold red)"
success_symbol = "[ʓ](bold blue)"

[cmd_duration]
disabled = true

[line_break]
disabled = true

[nodejs]
format = "via [🪢 $version](bold green) "

[python]
detect_files = []
detect_folders = [".direnv", "venv"]

[username]
show_always = true
