# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
[â•­â”€ [$username](italic)$directory$git_branch$git_status](bold green)
[â”‚](green) $all
[â•°â”€ $character](bold green)"""
scan_timeout = 10

[battery]
disabled = true

[character]
error_symbol = "[Ïˆ](bold red)"
success_symbol = "[Ê“](bold blue)"

[cmd_duration]
disabled = true

[line_break]
disabled = true

[nodejs]
format = "via [ðŸª¢ $version](bold green) "

[python]
detect_files = []
detect_folders = [".direnv", "venv"]

[username]
show_always = true
