add_newline = false
format = "[â•­ [$username](italic)$directory$git_branch$git_status](bold green)\n[âŽ¨](bold green) $all\n[â•°$character](bold green)\n"
scan_timeout = 10

[battery]
disabled = true

[character]
error_symbol = "[ Ïˆ](bold red)"
success_symbol = "[ Ê“](bold blue)"

[cmd_duration]
disabled = true

[line_break]
disabled = true

[nodejs]
format = "via [ðŸª¢ $version](bold green) "

[python]
detect_files = []
detect_folders = [".direnv", "venv"]

[username]
show_always = true
