[tools]
claude-code = "latest"
codex = "latest"
"github:BurntSushi/ripgrep" = "latest"
go = "latest"
hishtory = "latest"
jq = "latest"
starship = "latest"
zoxide = "latest"
age = "latest"
github-cli = "latest"
aws = { version = "latest", symlink_bins = "true" }
uv = "latest"
"pipx:tldr" = "latest"
rust = "latest"
"npm:skills" = "latest"
node = "latest"
bun = "latest"
herdr = "latest"
"cargo:typst-cli" = "latest"
ruby = "latest"
"pipx:ty" = "latest"
"go:github.com/boyter/scc/v3" = "latest"
hcloud = "latest"
shellcheck = "latest"
"github:cosmtrek/mindwalk" = "latest"
"pipx:pdfmerge" = "latest"
crystal = "latest"
watchexec = "latest"

[settings]
env_shell_expand = false
experimental = true

[hooks]
enter = """
projects_dir="$HOME/Projects"

case "$PWD" in
  "$projects_dir"/*)
    rel="${PWD#"$projects_dir"/}"
    project="${rel%%/*}"

    [ -n "$project" ] && figlet \
      -d "$HOME/.local/share/figlet/xero-figlet-fonts" \
      -f 'ANSI Shadow' \
      "$project"
    ;;
esac
"""
